### ISSUE TITLE
Medium Editor?

### ISSUE THREAD

**Issue by nearkingdom** [kenny-hibino/stories#1]
Hi Kenny, your tutorial series looks amazing. I think I'd quite like to give this a go.

Although you probably want to focus on your videos I had a suggestion for the the writing interface. Have you considered using [Medium Editor](http://yabwe.github.io/medium-editor/)?

**Comment by kenny-hibino** [comment]
Thanks! Glad you liked the tutorials. I actually heard of the editor in a podcast but never really looked into it. I will check it out and see if I like it. I've been using MacVim and it's been working great for me so far.

**Comment by nearkingdom** [comment]
Sorry, by "text editor" I mean a writing interface for your application. The Medium Editor adds an  inline editor toolbar to a text box.

**Comment by kenny-hibino** [comment]
Wow, this is exactly what I need in my application. Thanks for letting me know! Looks like there is a gem for this called "medium-editor-rails", so I will look into how to integrate that into the application.

**Comment by nearkingdom** [comment]
Nice - glad I could help.

**Comment by kenny-hibino** [comment]
Feel free fork this and create pull requests! Need to install and run Elasticsearch and Redis. I will update the README soon. Thanks again!
