### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by nearkingdom** [kenny-hibino/stories#2]
Hi Kenny, I cloned the app to have a play around with the code and make some pull requests - however when I run the app I get the following in my terminal:

`split_gem_path': undefined method `split'

Any idea why?

**Comment by kenny-hibino** [comment]
I haven't had that error before but try the following steps, and let me know if it solves the problem. 
1. Instal PostgreSQL, Elasticsearch and Redis. (if you're using mac I recommend Homebrew)
2. Make sure the Ruby version is correct. I'm using Ruby v.2.3.0
3. Run "bundle install"
4. Run Postgres, Elasticsearch, and Redis
5. Run "rails server"
6. Run "bundle exec sidekiq -q elasticsearch -q mailer -c 3"

Follow these steps and let me know if that solves the problem. Thanks for cloning my repo and feel free to make pull requests!!

**Comment by nearkingdom** [comment]
I did as you suggested but I'm still getting issues...

Here is the full error

`/Users/danlee/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:50:in `split_gem_path': undefined method `split' for #<Array:0x007f93e2b75778> (NoMethodError)
	from /Users/danlee/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/path_support.rb:32:in `initialize'
	from /Users/danlee/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb:351:in `new'
	from /Users/danlee/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems.rb:351:in `paths='
	from /Users/danlee/Sites/hobby/stories/bin/spring:11:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>`

**Comment by kenny-hibino** [comment]
I see that you are using rvm for Ruby versioning. Give rbenv a try. Here's a good instruction on that [https://gorails.com/setup/osx/10.10-yosemite](https://gorails.com/setup/osx/10.10-yosemite) and set the Ruby version to 2.3.0.

Let me know again, I'll try my very best to get you started on this project!

**Comment by nearkingdom** [comment]
Ok I imploded rvm and used rbenv. I'm using Ruby version 2.3.0. I made sure I installed PostgreSQL, Elasticsearch and Redis. Installed the gems and ran rails server. I now get the following error. Any ideas?

`Exiting
/Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect': Failed to open TCP connection to localhost:9200 (Connection refused - connect(2) for "localhost" port 9200) (Faraday::ConnectionFailed)
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:878:in `connect'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-mini-profiler-0.9.8/lib/patches/net_patches.rb:7:in `block in request_with_mini_profiler'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-mini-profiler-0.9.8/lib/mini_profiler/profiling_methods.rb:38:in `step'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-mini-profiler-0.9.8/lib/patches/net_patches.rb:6:in `request_with_mini_profiler'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:201:in `perform_request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/indices/create.rb:77:in `create'
	from /Users/danlee/Sites/hobby/stories/app/models/user.rb:86:in `<top (required)>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `load'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:457:in `block in load_file'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:647:in `new_constants_in'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:456:in `load_file'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:354:in `require_or_load'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `each'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `inject'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:566:in `get'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:597:in `constantize'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise.rb:292:in `get'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:81:in `to'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:76:in `modules'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:93:in `routes'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:160:in `default_used_route'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/mapping.rb:70:in `initialize'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise.rb:326:in `new'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise.rb:326:in `add_mapping'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:238:in `block in devise_for'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `each'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/devise-3.5.6/lib/devise/rails/routes.rb:237:in `devise_for'
	from /Users/danlee/Sites/hobby/stories/config/routes.rb:6:in `block in <top (required)>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/actionpack-4.2.5/lib/action_dispatch/routing/route_set.rb:412:in `draw'
	from /Users/danlee/Sites/hobby/stories/config/routes.rb:3:in `<top (required)>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialize!'
	from /Users/danlee/Sites/hobby/stories/config/environment.rb:5:in `<top (required)>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/danlee/Sites/hobby/stories/config.ru:3:in `block in <main>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/danlee/Sites/hobby/stories/config.ru:in `new'
	from /Users/danlee/Sites/hobby/stories/config.ru:in `<main>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/server.rb:61:in `app'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/server.rb:78:in `start'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/danlee/Sites/hobby/stories/bin/rails:9:in `require'
	from /Users/danlee/Sites/hobby/stories/bin/rails:9:in `<top (required)>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/spring-1.6.3/lib/spring/client/rails.rb:28:in `load'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/spring-1.6.3/lib/spring/client/rails.rb:28:in `call'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/spring-1.6.3/lib/spring/client/command.rb:7:in `call'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/spring-1.6.3/lib/spring/client.rb:28:in `run'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/spring-1.6.3/bin/spring:49:in `<top (required)>'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/spring-1.6.3/lib/spring/binstub.rb:11:in `load'
	from /Users/danlee/.rvm/gems/ruby-2.3.0/gems/spring-1.6.3/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/danlee/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/danlee/Sites/hobby/stories/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'`

**Comment by kenny-hibino** [comment]
Can you navigate to localhost:9200 in the browser and make sure that Elasticsearch is running?
It should look something like this
```javascript
{
  "status" : 200,
  "name" : "Atalanta",
  "cluster_name" : "elasticsearch_kenhibino",
  "version" : {
    "number" : "1.7.3",
    "build_hash" : "05d4530971ef0ea46d0f4fa6ee64dbc8df659682",
    "build_timestamp" : "2015-10-15T09:14:17Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by nearkingdom** [comment]
Ah looks like it wasn't running, odd. That seems to get past the issue but now it seems I need to create the database - how do I do that?

/Users/danlee/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect': FATAL:  database "stories_development" does not exist (ActiveRecord::NoDatabaseError)

**Comment by kenny-hibino** [comment]
Try running rake db:create and rake db:setup

**Comment by nearkingdom** [comment]
Sorry about this Kenny, I'm getting there little by little.

I now get a error saying:

/Users/danlee/.rvm/gems/ruby-2.3.0/gems/fog-1.23.0/lib/fog/rackspace/mock_data.rb:42: warning: key "name" is duplicated and overwritten on line 80
stories_development already exists
stories_test already exists
rake aborted!
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 1: SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LI...
                               ^
: SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LIMIT 1000

**Comment by kenny-hibino** [comment]
No worries! Try running "rake db:migrate"

**Comment by nearkingdom** [comment]
Ok now I get the following - it seems to be missing the table "users"...

/Users/danlee/.rvm/gems/ruby-2.3.0/gems/rack-mini-profiler-0.9.8/lib/patches/db/pg.rb:90:in `exec': PG::UndefinedTable: ERROR:  relation "users" does not exist (ActiveRecord::StatementInvalid)
LINE 1: SELECT  "users".* FROM "users"  ORDER BY "users"."id" ASC LI...

**Comment by kenny-hibino** [comment]
Just make sure that you are running Postgres and run rake db:migrate, and it should create all the tables you need

**Comment by kenny-hibino** [comment]
Let me know if you are still having trouble installing!

**Comment by nearkingdom** [comment]
Still struggling with this - I noticed that even though I imploaded rvm all the gems were getting installed in a rvm folder at /Users/danlee/.rvm/gems/ every time I ran bundle install. Should this be happening now that I'm using rbenv?

**Comment by kenny-hibino** [comment]
I haven't used rvm personally so I'm not sure if that's causing the issue. I will try installing on my other machine when I get home today, see if I can figure out what's causing the issue. I'll get back to you tonight

**Comment by nearkingdom** [comment]
Hi Kenny, did you have a go at this?

**Comment by kenny-hibino** [comment]
That first warning about "name" is something that's been around for a long time. I haven't gotten a chance to look into it. So don't worry about the first warning. 
Try commenting out user.rb and post.rb and run rake db:migrate and uncomment the files after migration is complete. It might have something to do with synching data in Elasticsearch with Postgres

**Comment by nearkingdom** [comment]
Where do uncomment that out? Are you talking about the models?

**Comment by kenny-hibino** [comment]
After the class definition you will see a few lines of code that's related to importing data into Elasticsearch, comment out those line and see if rake db:migrate works.

**Comment by nearkingdom** [comment]
Ok that worked! I'm live and ready to rumble.

**Comment by kenny-hibino** [comment]
Sweet!! Thanks for your patience man. 

Start by creating a topic branch with Git and play around with it. 

To set the featured tags, you have to first create an admin user. ( Create an admin from Rails console and type something like "Admin.create(email: 'your@email.com', password: 'password', password_confimation: 'password')"

After that navigate to localhost:3000/admins/sign_in and input your email and password. and click on tags and you will see feature button and clicking on it will make the tag a featured tag. 

Hit me up if you have any questions!

**Comment by nearkingdom** [comment]
Ok - I tried running Admin.create(email: 'your@email.com', password: 'password', password_confimation: 'password') in the rails console and I get the following

ActiveRecord::UnknownAttributeError: unknown attribute 'password_confimation' for Admin.

**Comment by kenny-hibino** [comment]
sorry it's just I made a typo there. it's 'password_confirmation' and i would replace those values with my own email and password

**Comment by nearkingdom** [comment]
Brilliant - this project is ace!

**Comment by nearkingdom** [comment]
Was just about to make pull request on a topic branch. Github for Mac is telling me I may not have permission to access Stories? I just wanted to check if this was the case?

**Comment by kenny-hibino** [comment]
Do you mind telling me what change you made?

**Comment by nearkingdom** [comment]
Sure - I have improved the reading experience - using the serif font instead of a san serif font in posts and the editing panel.

- Added serif google font “Lora” to assets,
- Added Font Stack variables
- Created a mixin sass file
- Created mixin called “well-read” for stories and editing area - can now be changed in one place!
- Added minor styles for padding on read-me and pages

<img width="780" alt="screen shot 2016-03-05 at 17 56 27" src="https://cloud.githubusercontent.com/assets/7198242/13549376/af6f09bc-e2fb-11e5-8e2c-9f1f5336c087.png">

**Comment by kenny-hibino** [comment]
Looks cool! I'll add you to the contributor list. Just make sure you make a topic brach and push it up. So that I can take a look at the changes you made. 

Do you have a background in design? I could use some help in organizing Sass files in this project

**Comment by nearkingdom** [comment]
Yes I'm a designer. That was my first Pull Request (on Github). I reckon if there was some good readme with instructions more people might contribute. Why did you begin the project? Just to learn?

**Comment by kenny-hibino** [comment]
Yep,  this started out as a little personal side project so that I can learn Ruby on Rails and React and other JavaScript libraries. It came out pretty decent so I decided to do a youtube series based on the project to help other people learn the technologies.

I agree. This project needs a good README to bring more people in. Do you mind writing a README for this project? You can use markdown or whatever format you want.

And let me know if you have ideas for new features or designs for this project. My email is ken.hibino7@gmail.com. Thanks for your first pull request!
