### ISSUE TITLE
Would you like to share how to set up OAuth configuration? 

### ISSUE THREAD

**Issue by PHI33** [kenny-hibino/stories#26]
Thank you very much!

**Comment by milezzz** [comment]
@PHI33 I realize this is closed but any chance you could help with this?  I keep getting a ```401 Authorization Required``` when I try with Twitter Oauth.  I put my credentials in secrets.yml - anything I am missing?

Do we need to set a callback URL within Twitter's controls? I left that blank.

**Comment by SavvasTheodorou** [comment]
I don't think it will work. Add your homepage

**Comment by milezzz** [comment]
Yep thanks forgot to update this thread.  Required a callback URL. I used http://mydomain
