### ISSUE TITLE
_feed.html.erb it seems not work!

### ISSUE THREAD

**Issue by omartorresrios** [kenny-hibino/stories#33]
Hi,

Feed.rb logic does work, but does not display the icon tag or the name. Nor if a post recommended does not show "Recommended by Stories ... and other 5".
Why is this happening?

Thanks!

**Comment by kenny-hibino** [comment]
this has been fixed since https://github.com/kenny-hibino/stories/commit/dddac06d26a530eaa12496bbf2452f578861f8d4
