### ISSUE TITLE
Feed elements bug (does not appear)

### ISSUE THREAD

**Issue by omartorresrios** [kenny-hibino/stories#38]
Someone could find and fix the bug on the elements of the feed that no longer appear? @kenny-hibino 
What do I mean? Here an image:

![unnamed](https://cloud.githubusercontent.com/assets/14302316/22210151/d9fd85c8-e156-11e6-8bf8-5ffdd7eecb39.png)

I tried to return to the version of rails 4.2.4 and still does not appear. That functionality was cool 🙁 .

**Comment by kenny-hibino** [comment]
@omartorresrios Thank you for bringing this up! I remember this started to break when I upgraded rails version. Need to look into this.

**Comment by kenny-hibino** [comment]
This has been fixed since commit dddac06d26a530eaa12496bbf2452f578861f8d4 👍
